name: record_android
description: Android specific implementation for record package called by record_platform_interface.
version: 1.0.2
homepage: https://github.com/llfbandit/record/tree/master/record_android
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface: 
    path: ../record_platform_interface

flutter:
  plugin:
    implements: record
    platforms:
      android:
        package: com.llfbandit.record
        pluginClass: RecordPlugin
