name: record_windows
description: Windows specific implementation for record package called by record_platform_interface.
version: 1.0.0
homepage: https://github.com/llfbandit/record/tree/master/record_windows
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface:
    path: ../record_platform_interface
  path: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.3

flutter:
  plugin:
    implements: record
    platforms:
      windows:
        pluginClass: RecordWindowsPluginCApi
